# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Generate release name
      id: release_file_name
      run: |
          echo "release_file_name=seo-helper-qwik_$(date +'%Y-%m-%d_%H%M%S')${{ github.sha }}.zip" >> $GITHUB_ENV
    - run: echo "ket qua ${{ env.release_file_name }}"
