name: Build extension

on:
  push:
    branches: [ "main" ]

env:
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build.ext
    - name: Generate release name
      id: release_file_name
      run: |
          sha_short=$(git rev-parse --short HEAD)
          echo "release_file_name=seo-helper-qwik_$(date +'%Y-%m-%d_%H%M%S')_$sha_short.zip" >> $GITHUB_ENV
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: ${{ env.release_file_name }}
        directory: dist
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.release_file_name }}
        artifacts: dist/${{ env.release_file_name }}
