# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Generate release name
      id: release_file_name
      run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "release_file_name=seo-helper-qwik_$(date +'%Y-%m-%d_%H%M%S')_${{ env.sha_short }}.zip" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build.ext
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: ${{ env.release_file_name }}
        directory: dist
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.release_file_name }}
        artifacts: dist/${{ env.release_file_name }}
